### ISSUE TITLE
RSSFE-07 Teams page queries and mutations

### ISSUE THREAD

**Issue by MadaShindeInai** [rolling-scopes-school/RSS-Teams-FE#13]
- [x]  click on the part closer to the edge of select do nothing. fix markup
- [x]  click + without value add empty divs
- [x] remove modal button and modal window from TeamsList
- [x] add check before submission **IF USER HAVE AT LEAST 1 course**. If no - show him an error.
- [x] NOW merge to dev
_____________________________________
- [x] investigate react-hook-form
- [x] add onChange fields validation
- [x] refactor component: add dynamic input generation, remove duplication

**Comment by Malagor** [comment]
Нотификация работает следующим образом. Я сперва сделал через таймер, а потому передумал и сделал так: если не выбран ни один курс при сабмите, то выдается нотификация. Убирается она при успешном выборе первого курса. Тог есть выбираем курс и на плюсик нажимаем. Тогда сообщение пропадает.
