### ISSUE TITLE
RSSFE-44 Admin page

### ISSUE THREAD

**Issue by yuliaHope** [rolling-scopes-school/RSS-Teams-FE#144]
As an admin I want add courses and the max acceptable number of students per team on the course.

AC:

- add admin page
- add courses tab
  - list all active courses
  - add control to define a new course name
  - add control to define the number of students per team on the course
  - add save button
- after pressing the "save" btn, the course should be added to the list of active courses

**Comment by MadaShindeInai** [comment]
Need to add ability to remove courses when registration are closed ( for example after sorting)

**Comment by MadaShindeInai** [comment]
Also if we will got admin page - we can move sorting button there.
Also we do not need any special styling for admin page. Just common style.

**Comment by MadaShindeInai** [comment]
Feature: Mentor

Registration / Edit profile flow :
- add select with 2 options: Student / Mentor, and title - Role.
- Student role stay the same, Mentor have at least 1 messenger required and score - null (do not show input).

Dashboard:
- stay the same (we are not showing mentors there at all)

Teams:
- in team-header we have only 2 buttons - Join as a mentor / Leave course(works the same way). 
- when mentor clicks 'Join' button - everything works the same and he joins the team as mentor.
- In team we display mentors on the first line of the table. In score field we write - Mentor, in № field we write nothing . In empty messenger field we write '—' if it exists.  We can use bold font and ??? font color to mark mentor.
- Mentor does not in any way affect the team limit. 
Example 1: Mentor + 3 members = 3 members. 
Example 2: Team have 1 member and mentor. Member leave team => we remove mentor from a team => destroy team.

**Comment by MadaShindeInai** [comment]
**BE:**
- crud for courses ( create, edit, read, enable/terminate). When we creating course it should be disabled as default.
- set disabled for all courses
- add status/team size field for all courses
- validate course name (RSS *** 202* Q*)
