### ISSUE TITLE
RSSFE-13 Add mutations to the project

### ISSUE THREAD

**Issue by besovadevka** [rolling-scopes-school/RSS-Teams-FE#37]
- [x] add addUserToTeam mutation
- [x] add removeUserFromTeam mutation
- [x] add createTeam mutation
- [x] add updateTeam mutation
- [x] make modal to use updTeam mutation where you will enter new link
- [x] add animation on password copy (ask malagor how)

**Comment by MadaShindeInai** [comment]
done
